# Generated by Django 4.1.3 on 2022-12-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailhistory_alter_authtokens_user_id_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emailhistory',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
